### ISSUE TITLE
Convert Mobile to Hi-Fi designs

### ISSUE THREAD

**Issue by MertonL** [emfoundation/smf-prototype#100]
- [x] General Alignment towards hifi designs
- [ ] Learning Path dropdown menu (not previous/next buttons)
- [x] Fix issue of white bar displaying (Due to rotated css burger menu in nav) - only seems to be an issue on real devices.
- [ ] Mobile text root size: 16px, desktop 18px
- [x] About Page Mobile version (no images)

**Comment by georgemillard** [comment]
Hey @asimonw, just spotted that the mobile design for the about page has taken the desktop version away from its initial design:

![screen shot 2018-06-18 at 09 07 16](https://user-images.githubusercontent.com/25058990/41524957-3c6a9f3a-72d7-11e8-89fb-df937f27ff2a.png)

The inner text is meant to be in the wrap - and therefore inline with the back button - not the outer block.

**Comment by asimonw** [comment]
@georgemillard I wrapped things inside of a Bulma container to make the margin issues on mobile go away, but I think I can simply make that a fluid container. Otherwise it'll require a bit more fiddling. I'll have a look.

**Comment by MertonL** [comment]
Leaving the last two unfinished checkboxes:
1. Learning Path dropdown menu
2. Mobile text root size: 16px, desktop 18px
As they require too much time at this point, will close this issue now and reopen as separate issues.
