### ISSUE TITLE
Update burger menu and create About Page, including for mobile

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#101]

**Comment by MicrosoftDan** [comment]
Are we all happy with using this for the link to the about page...
![screen shot 2018-05-31 at 16 25 23](https://user-images.githubusercontent.com/36270652/40837070-062ce886-6591-11e8-81a5-c1e1e8ffd405.png)

**Comment by MicrosoftDan** [comment]
![screen shot 2018-06-01 at 11 45 58](https://user-images.githubusercontent.com/36270652/40837157-656533f8-6591-11e8-88bb-8fe4e20ccc62.png)

**Comment by MicrosoftDan** [comment]
and layout concept for 'about' page... images are just holding ones
![about](https://user-images.githubusercontent.com/36270652/40840932-9933f91c-65a0-11e8-9b5a-21a6fc8f445a.jpg)

**Comment by colinwebster75** [comment]
looks good! Can we use hyperlinks in the text?

**Comment by kareninsignares** [comment]
I also agree, looking good! :)

**Comment by MicrosoftDan** [comment]
It will be hardcoded so yes it will be just wrapping a link tag around the text you want highlighted. Link colour the same blue as what is being used in rest of design? @georgemillard can you just confirm that we can add links please.

**Comment by georgemillard** [comment]
@MicrosoftDan Looks really smart :-) 
@colinwebster75 Content will be hardcoded so links will be fine.
