### ISSUE TITLE
On a Learning Path, the browser back button is currently not working.

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#120]
Once you have viewed a few chapters, and you are on a chapter with embedded content (ie YouTube video) pressing the browser "Back" button will update the embedded content correctly to the previous chapter, but not the rest of the page.

A _second_ click of the "Back" button brings the rest of the page up to date.

This happens as the iFrame inserts an extra step in the history as it loads.

**Comment by georgemillard** [comment]
@kareninsignares Could you prioritise this in the ToDo list, please? Give me a shout if you need more info.

**Comment by asimonw** [comment]
Should be solved with the PR for #97
