### ISSUE TITLE
Add SASS and Bulma to Nuxt

### ISSUE THREAD

**Issue by asimonw** [emfoundation/smf-prototype#13]

**Comment by MertonL** [comment]
@asimonw Currently, if I want to use SASS variables from the stylesheets, I have to import on every page/component I want it on. It seems that the CSS selector in the config loads it as if it's normal CSS and not SCSS - see [this nuxt issue](https://github.com/nuxt/nuxt.js/issues/1092) for others experiencing similar issues.

**Comment by asimonw** [comment]
@MertonL what do you mean by "the CSS selector in the config"? And are you saying that it works fine if you import the file for every component? That might be a bit tedious, but would at least work for now. In the issue you refer to, some people do seem to suggest some solutions, although I haven't checked in detail.

You can also set some global classes to add colours etc. You can either do that through `main.scss` or  in a layout file.

**Comment by MertonL** [comment]
@asimonw I mean about this line:
https://github.com/emfoundation/smf-prototype/blob/b7a9bbdee18893e9f774b7b6007fa2c3e298fc70/nuxt.config.js#L48

Although this normally means that the linked CSS is available on every page & component, it doesn't seem to import the SASS variables, so If I try and use them in a component, I get this error:
`background-color: $secondary; ^ Undefined variable: "$secondary"`, so my work around was to include `@import '~/assets/scss/main.scss';` where I needed variables.

**Comment by MertonL** [comment]
Cheers, @asimonw, maybe with Nuxt.js V2.0 it'll be better ay. Will close this issue
