### ISSUE TITLE
Add EMF Favicon - as used on the EMF website

### ISSUE THREAD

**Issue by vicky-d1** [emfoundation/smf-prototype#132]
Should we add the EMF logo for the testing period until it has it's own brand?

Karen/Dan this may be something for you guys to decide?

**Comment by dalwal08** [comment]
I think we should.

**Comment by kareninsignares** [comment]
I think so as well. @vicky-d1 How easy/ time-consuming is to do an EMF logo favicon?

**Comment by MicrosoftDan** [comment]
Can we use the existing favicon off EMF site? I can generate one if need be?

**Comment by vicky-d1** [comment]
Let's use existing, shouldn't be too much work. Just need to prioritise @kareninsignares :)

**Comment by kareninsignares** [comment]
@vicky-d1 @MicrosoftDan Done! Already prioritised all the tasks.
