### ISSUE TITLE
Question Page - character limit on Answer boxes to avoid text overflow

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#142]

**Comment by MertonL** [comment]
@kareninsignares The character limit to prevent breaking will be 128 characters for the text. This is made to work with the changes that will be implemented as of issue #90 

The Answer titles is trickier to limit as it more depends on word lengths (and how many), but a max of 50 characters should prevent issues. Should be checked on a per answer basis just incase.

**Comment by kareninsignares** [comment]
Many thanks, @MertonL! Super helpful! There you go @dalwal08, now you can create with constraints! ;)

**Comment by dalwal08** [comment]
Wonderful!
