### ISSUE TITLE
Banner - grey banner overlay

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#145]
@MicrosoftDan suggests a grey overlay of: 
rgba (73, 80, 98, .9)

![image](https://user-images.githubusercontent.com/25058990/41590497-0850a3ce-73af-11e8-8c1a-c4bf8820844c.png)

**Comment by kareninsignares** [comment]
![screen shot 2018-06-19 at 10 06 53](https://user-images.githubusercontent.com/35805645/41588055-9bb22c98-73a8-11e8-8f43-d93c0c241031.png)

**Comment by MicrosoftDan** [comment]
It will be in my notes I send over buddy :)

**Comment by MicrosoftDan** [comment]
![screen shot 2018-06-19 at 08 40 06](https://user-images.githubusercontent.com/36270652/41590579-3d10620c-73af-11e8-8828-f7d337f5ba94.png)
