### ISSUE TITLE
Home Page - Character limit for Let Us Guide You and Explore descriptions

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#148]

**Comment by MertonL** [comment]
@kareninsignares @dalwal08 I added the static text for the homepage, but even after design tweaks it is too long - especially for mobile. Ideally the content is the same for desktop and mobile
The character limit should be ~128 characters for each paragraph if doable, this then makes both options fit on screen for mobile (for iphone 5), with restricted char:
![screen shot 2018-06-21 at 10 46 25](https://user-images.githubusercontent.com/25505506/41711533-33953d14-7540-11e8-83e9-30f98984432b.png)
![screen shot 2018-06-21 at 10 46 40](https://user-images.githubusercontent.com/25505506/41711538-359ee646-7540-11e8-9234-471b9393a749.png)
