### ISSUE TITLE
Home Page - Remove 'M' from Explore Photo

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#150]
- [x] Photo edited
- [x] Photo uploaded

**Comment by MicrosoftDan** [comment]
Hows this? :)
![landing-explore-web](https://user-images.githubusercontent.com/36270652/41836150-bc39c554-7851-11e8-80b3-8d8d5edc55fb.jpg)

**Comment by dalwal08** [comment]
Tested, looks good!
