### ISSUE TITLE
Update About Page with Banner copy and image

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#153]

**Comment by kareninsignares** [comment]
@dalwal08 To provide the content for this part and send it to @MicrosoftDan

**Comment by MicrosoftDan** [comment]
Hi All, for all copy please now send to George and Mert as I can't add it to the hardcoded code but they can. Ta

**Comment by dalwal08** [comment]
Is this different to this issue - https://github.com/orgs/emfoundation/projects/5#card-10682357 ?

**Comment by kareninsignares** [comment]
@dalwal08 yes, is the same. We have so many tasks that we doubled a couple. #147 is the content task, this one is the dev task for the developers :)
