### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#155]
- [x] 1. Back button
- [x] 2. List Item increase min height reduce title size mobiles
- [x] 3. Top Nav balance left/right padding
- [x] 4. Banner increase description width 
- [x] 5. Chapter nav design update
- [x] 6. Chapter/Answer consistent smaller body text width
- [x] 7. Quote block design update
- [x] 8. Answer box - reduce Title font size and line height when on two lines, equalise margins (to thinner one)
- [x] 9. Mobile text sizing
- [x] 10. Mobile back button alignment
- [x] 11. Mobile Answer Page tweaks - see below

Notes: https://docs.google.com/document/d/1lZlwsz1yE0omKlR5zjtpkqJXXdwZNfYGvGsYC8JlNro/edit

**Comment by georgemillard** [comment]
![image](https://user-images.githubusercontent.com/25058990/41592505-aeebc70e-73b4-11e8-81d1-65b6dfb9c9ff.png)

**Comment by georgemillard** [comment]
@kareninsignares please prioritise these design tweaks in the to do list :)

**Comment by MicrosoftDan** [comment]
Sorry, guys, just seen one more tweak pleasies...
On Answer pages in mobile please can I have the sub heading reduced to 1.5 em and also have my blue line added back in. :) I just quickly edded the blue line into expect element.
![screen shot 2018-06-19 at 11 57 11](https://user-images.githubusercontent.com/36270652/41593544-5a30990c-73b8-11e8-95e4-9fa0009c0961.png)
![screen shot 2018-06-19 at 12 01 07](https://user-images.githubusercontent.com/36270652/41593591-80a5aa28-73b8-11e8-85d3-25d0513c94db.png)

**Comment by MicrosoftDan** [comment]
Not this...
![screen shot 2018-06-19 at 12 09 17](https://user-images.githubusercontent.com/36270652/41593953-a5df8844-73b9-11e8-95d7-d43118e59fb0.png)

**Comment by MicrosoftDan** [comment]
This is mobile with banner background colour change, back button aligned, and font sizes changed...
![screen shot 2018-06-19 at 13 39 30](https://user-images.githubusercontent.com/36270652/41597770-48746334-73c6-11e8-9cab-9bb0387cbd2a.png)
