### ISSUE TITLE
Learning paths chapters overflow the width when 10 or more are present

### ISSUE THREAD

**Issue by MertonL** [emfoundation/smf-prototype#161]
This happens for smaller "tablet" sized screens.
![screen shot 2018-06-25 at 11 15 36](https://user-images.githubusercontent.com/25505506/41844741-07a2cb1e-7869-11e8-9ded-340eb7adc0ad.png)

@MicrosoftDan any suggestions for what you would like to happen in this scenario?

**Comment by MertonL** [comment]
One quick solution would be to use the mobile navigation for tablet also

**Comment by MicrosoftDan** [comment]
I would suggest using the mobile version from tablet down mate
