### ISSUE TITLE
Search: "Take me back!" button

### ISSUE THREAD

**Issue by kareninsignares** [emfoundation/smf-prototype#175]
@MicrosoftDan to create a mockup of the "Take me back!" button. 

![screen shot 2018-07-08 at 13 59 44](https://user-images.githubusercontent.com/35805645/42420026-816d188e-82b7-11e8-859b-d500e03f66fc.png)

**Comment by MicrosoftDan** [comment]
How about either of these :)
![take me back link](https://user-images.githubusercontent.com/36270652/42437943-7c5e030e-8356-11e8-976a-8c528bcda9b5.jpg)
