### ISSUE TITLE
Slideshare not embedding correctly

### ISSUE THREAD

**Issue by dalwal08** [emfoundation/smf-prototype#179]
Slideshows imported from Slideshare are not displaying.

![screen shot 2018-07-10 at 10 16 19](https://user-images.githubusercontent.com/11637473/42500919-6ac1f126-842a-11e8-9591-09ae9f5b9b05.png)

**Comment by dalwal08** [comment]
@asimonw I'm not sure. The Building Blocks one is working though. https://prototype.circulareconomy.space/learning-paths/4/9

**Comment by asimonw** [comment]
@dalwal08 That one's indeed fetched through HTTPS.

I don't have access to the "DAM" for this prototype, but could you try the same url for the Recap but with HTTPS instead? I.e, https://www.slideshare.net/slideshow/embed_code/key/DaSJ2SueWfJZHx

**Comment by dalwal08** [comment]
@asimonw That's done the trick! Baie Dankie!
