### ISSUE TITLE
What is CE content for design sprint prototype

### ISSUE THREAD

**Issue by kareninsignares** [emfoundation/smf-prototype#186]
Molly, Lou & Dale to flesh out content for the Mercury design sprint prototype, getting input from Sed & Joe I when pertinent. (Dale: overview all content process)
 
Tasks: 

- [x] Momentum piece
- [x] Story
- [x] Definition (SEO friendly)
- [x] Next steps/onward paths for users
- [x] Graphics/Stats 
- [x] Review content with Seb, Jo Iles

**Comment by kareninsignares** [comment]
@dalwal08 Did I forget other tasks?

**Comment by dalwal08** [comment]
No that was everything I reckon.
