### ISSUE TITLE
Decide on which Topic Group/Topics we need for SMF Prototype content + Descriptions for each

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#19]
Each Asset within the SMF Prototype will need topics attached to it. These should ideally be chosen from our existing topic list if possible:
(see circulareconomy.space/admin/file_manager/tag/ contact @georgemillard if you need an account)
If new topics are needed, these need to be validated before expanding our taxonomy.

Each Topic Group needs a description - who is responsible for writing these?

**Comment by kareninsignares** [comment]
Colin and Gail will keep working on the content for the pilot, and it will be ready next Friday 27th April. SMF Team will be able to provide the topic list we need after they finish curating the content.

**Comment by dalwal08** [comment]
Colin will be adding tags to each individual piece of content in the next week from the Taxonomy.

**Comment by asimonw** [comment]
@georgemillard I'm assuming that we'll still want to work with one "topic cloud" for everything on the DAM right? Otherwise it could messy very quickly.
