### ISSUE TITLE
User Story 3. Search (register interest)

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#40]
As a user I want to free text search content for specific topics/keywords so that I can quickly find resources relevant to me in my work/area/industry.

Step one will be a modal pop up saying "Coming soon", registering the user's interest
- [x] Modal design
- [ ] Get copy
- [x] Implement

We've got the copy, but waiting for final input from the editorial team before sharing. If they don't get back to us before Friday morning we will go with:

Thanks for your interest
Now we know you want it, search will be coming soon
Take me back!
(Or something like this)

**Comment by georgemillard** [comment]
Step one will be linking to an empty page and registering interest

**Comment by MertonL** [comment]
@vicky-d1 @kareninsignares FYI Vicky is to come up with text for the search page: 
![screen shot 2018-06-20 at 09 18 00](https://user-images.githubusercontent.com/25505506/41646019-a1b9ace8-746a-11e8-9caf-a5431e8d311f.png)

**Comment by kareninsignares** [comment]
Great! Looking good already!
