### ISSUE TITLE
User Story 12 Learner Path Completion Page

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#52]
As a user I want to be presented with a Learner Path Completion Page to include congratulations, what to do with what I have learnt and where to go next so that I am rewarded for my efforts and know what the next steps in my learning are.

**Comment by kareninsignares** [comment]
We want to add:
- Text
- Links
- Polls - Survey Monkey for feedback

**Comment by georgemillard** [comment]
Issue fulfilled by #133
