### ISSUE TITLE
Format of embedding powerpoints on the asset page & learner pathways

### ISSUE THREAD

**Issue by MertonL** [emfoundation/smf-prototype#60]
Hey @GailWillows, @colinwebster75 and @kareninsignares.

 An issue was raised when we demoed the prototype about the look of the powerpoints, and that the buttons seemed confusing with the design on the page:

![screen shot 2018-05-10 at 09 55 52](https://user-images.githubusercontent.com/25505506/39861586-f0f98622-5438-11e8-97d3-2d10b9a5b896.png)

The current method uses google drive which is not flexible for us to change the look of it, it also means it has to be hosted on Google Drive, which is not ideal for consistency of where the assets are stored. 

My suggestion, would be to convert the Powerpoints to PDF, from which they can be displayed in a similar format to how the documents/reports we saw were displayed:

![screen shot 2018-05-10 at 10 06 50](https://user-images.githubusercontent.com/25505506/39861855-dafa5a9e-5439-11e8-944c-db14d89aec20.png)

On the content side, this would require a small amount of work per Powerpoint, but is a simple process to export as a PDF. 
It'd be great to know your thoughts on this, and if you are happy or not for Powerpoints to be stored as PDFs. 

Thanks!

**Comment by colinwebster75** [comment]
Hi Merty. Thanks for investigating this. Agreed that Google Slides is doubly problematic, but the PDF example you shared is not a winning alternative, unfortunately. The scrolling down isn't a suitable way to access the content - it needs to be a left and right arrow. (apart from the fact the PDF version doesn't do left and right scroll, being able to see more than one slide at a time is a little ugly and confusing).

Could you have a look at [slideshare](https://www.slideshare.net/ColinWebster2/its-all-about-soil) (has a much more prominent set of arrows), or, er...I struggled to find others. There must be others! Slideshare is pretty nice but even that is flawed (particularly the connection to someone's LinkedIn account).

If we can't find something better than Slideshare or Google Slides then I recommend we stick with Google Slides for now.

**Comment by MertonL** [comment]
Thanks @colinwebster75, Slideshare was on my radar, and it seems like a good solution and works nicely so thanks for the suggestion. 

![screen shot 2018-05-10 at 14 11 53](https://user-images.githubusercontent.com/25505506/39871270-2869ab64-545c-11e8-9930-e0f6172d4594.png)

This would require all powerpoints to be uploaded to Slideshare, then an asset created on the DAM with a link to the slideshare doc, just like youtube videos - the most important part here is what the link is, which would have to be the embed URL and not the URL you normally use to navigate.
Ie, 
`https://www.slideshare.net/slideshow/embed_code/key/qyNH3pdN0kMO78`
and **NOT** 
`https://www.slideshare.net/ColinWebster2/its-all-about-soil`

This can be found like so: 
![slideshare](https://user-images.githubusercontent.com/25505506/39871728-a7a3de8a-545d-11e8-9e2a-f764d6b5ad1c.jpg)

Note that only the circled info in the Embed box is required and not the other code. Hope this makes sense!
