### ISSUE TITLE
Low-fi mock-ups for Questions Page and Answer Page

### ISSUE THREAD

**Issue by georgemillard** [emfoundation/smf-prototype#65]

**Comment by MicrosoftDan** [comment]
![questions](https://user-images.githubusercontent.com/36270652/39865958-957e57f6-5446-11e8-8621-7cf2c162cbd3.jpg)

**Comment by MicrosoftDan** [comment]
![answer page](https://user-images.githubusercontent.com/36270652/39865981-a9fa74f8-5446-11e8-980e-43ba736db9bb.jpg)
