### ISSUE TITLE
Chapter hover depicts current chapter name, rather than the name of the chapter you are hovering over.

### ISSUE THREAD

**Issue by kareninsignares** [emfoundation/smf-prototype#77]
http://smfprototype.circulareconomy.space/learnerjourneys/4

![screen shot 2018-05-18 at 14 35 03](https://user-images.githubusercontent.com/35805645/40237547-af605274-5aa8-11e8-85e6-ce3b9461d75e.png)

**Comment by MertonL** [comment]
@kareninsignares Thanks for spotting it! It happened when me and @georgemillard merged our changes together - I've already fixed it and it will come in my next Pull request :)

**Comment by MertonL** [comment]
@kareninsignares On staging, please test! :)

**Comment by kareninsignares** [comment]
All good!
