### ISSUE TITLE
Uploaded image too large

### ISSUE THREAD

**Issue by dalwal08** [emfoundation/smf-prototype#78]
Uploaded an image to a chapter and it is so large that it doesn't display properly.
![screen shot 2018-05-18 at 14 38 21](https://user-images.githubusercontent.com/11637473/40237724-2c237160-5aa9-11e8-9473-cd41e44ff3df.png)

http://smfprototype.circulareconomy.space/learnerjourneys/4

**Comment by MertonL** [comment]
Thanks @dalwal08, I'll have a look into this.

**Comment by MertonL** [comment]
@dalwal08 Fixed and is on staging - please test! :)

**Comment by dalwal08** [comment]
Thanks @MertonL I've taken a look and it looks good. Does this mean that we don't have the ability to zoom into the images now?

**Comment by MertonL** [comment]
@dalwal08 Unfortunately the ability to zoom was a biproduct of the bad sizing, if the image size is uploaded correctly, there shouldn't be a need for zooming. However, It is possible to implement if you think it is needed.

**Comment by dalwal08** [comment]
@MertonL for the purposes of the prototype I don't think that's a priority.

**Comment by MertonL** [comment]
Thanks for clarifying, @dalwal08. I'll close this issue then.
