### ISSUE TITLE
SMF Team to select thumbnail images for the prototype.

### ISSUE THREAD

**Issue by kareninsignares** [emfoundation/smf-prototype#85]

**Comment by kareninsignares** [comment]
The SMF team needs to select the thumbnail images that will go in the prototype and share them with Dan B. If in doubt where to find images without copywriting issues please ask Dan B or the other design gurus.

**Comment by kareninsignares** [comment]
@GailWillows and @dalwal08 Did you provide all the images already? Just checking because I'm not quite sure where are we at with the thumbnail images for the prototype.

**Comment by dalwal08** [comment]
I believe we have provided all of the images that we can't change ourselves in the CMS.

**Comment by MicrosoftDan** [comment]
yup, all static images are done :)

**Comment by kareninsignares** [comment]
Great! Thanks, guys. Just wanted to make sure we had everything before closing the issue.
